# Generated by Django 5.2.11 on 2026-02-27 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='booking.seatlayout')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_locks', to='booking.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='booking_sea_expires_b6b82d_idx')],
                'unique_together': {('trip', 'seat')},
            },
        ),
    ]
